name: pipeline
on: push

jobs:
  check-format:
    name: check format
    env:
      working-directory: ./senile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install nightly
        run: |
          rustup default nightly
      - name: check formatting
        working-directory: ${{ env.working-directory }}
        run: |
          cargo fmt -- --check

  build:
    name: check (${{ matrix.name }})
    env:
      working-directory: ./senile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: "default"
          features: ""
    steps:
    - uses: actions/checkout@v1
    - name: install toolchain
      run: rustup default stable
    - name: install tools
      run: sudo apt-get install build-essential
    - name: execute unit tests
      working-directory: ${{ env.working-directory }}
      run: cargo test ${{ matrix.features }}
    - name: build program
      working-directory: ${{ env.working-directory }}
      run: cargo build --release --locked ${{ matrix.features }}
