name: wiki
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docs/**
      - .github/**

jobs:
  website:
    name: website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: prepare
        run: |
          cargo +stable install senile
          mkdir -p ./docs/out
          cp ./docs/README.adoc ./docs/out/
          senile collect -f="(\.rs|\.py)$" --format="// TODO!(,):" --format="# TODO!(,):" -p . | ./docs/wiki/src/todos.py >> ./docs/out/README.adoc
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/out
          publish_branch: wiki
