name: wiki
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docs/**
      - .github/**

jobs:
  website:
    name: website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: install
        run: |
            cargo +stable install senile
            sudo apt install hugo
            npm i -g asciidoctor
      - name: prepare
        run: |
          senile collect -f="(\.rs|\.py)$" --format="// TODO!(,):" --format="# TODO!(,):" -p . | ./docs/todos.py >> ./docs/wiki/content/docs/todos.adoc
          cd docs/wiki
          hugo
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/wiki/public
          publish_branch: wiki
