name: wiki
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docs/**
      - .github/**

jobs:
  website:
    name: website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with: 
          submodules: true
      - name: install
        run: sudo apt-get install build-essential && cargo install mdbook --version=0.4.7
      - name: prepare
        run: |
          cargo install senile
          senile collect -f="(\.rs)$" -p . | ./docs/wiki/src/todos.py >> ./docs/wiki/src/todos/root.md
      - name: build
        working-directory: docs/wiki
        run: mdbook build
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/wiki/book
          publish_branch: wiki
